# Generated by Django 3.2.16 on 2022-11-16 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('desc', models.TextField()),
                ('url_img', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Image_not_available.png/640px-Image_not_available.png')),
                ('active', models.BooleanField(default=True)),
                ('crisis', models.TextField()),
                ('allocation_amount', models.IntegerField(default=0)),
                ('presentation_url', models.URLField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=255)),
                ('holder_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
                ('ifsc', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inverst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('amount', models.FileField(upload_to='')),
                ('id_proff', models.FileField(upload_to='idproof/')),
                ('income_certificate', models.FileField(upload_to='income/')),
                ('is_approved', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=255)),
                ('holder_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
                ('ifsc', models.CharField(max_length=20)),
                ('passbook_copy', models.FileField(upload_to='passbook/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
