# Generated by Django 3.2.16 on 2022-11-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inversterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversterprofile',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inversterprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inversterprofile',
            name='holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inversterprofile',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
