# Generated by Django 3.2.16 on 2022-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221120_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverst',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inverst',
            name='metamask_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
