# Generated by Django 3.2.16 on 2022-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_inversterprofile_metamask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverst',
            name='transction_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
