# Generated by Django 3.2.16 on 2022-11-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221120_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='raised',
            field=models.BooleanField(default=False),
        ),
    ]
